from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_second_window(object):
    def setupUi(self, second_window):
        second_window.setObjectName("second_window")
        second_window.resize(295, 309)
        second_window.setMinimumSize(QtCore.QSize(295, 309))
        self.centralwidget = QtWidgets.QWidget(second_window)
        self.centralwidget.setObjectName("centralwidget")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(210, 240, 75, 23))
        self.run.setObjectName("run")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.code = QtWidgets.QTextEdit(self.centralwidget)
        self.code.setGeometry(QtCore.QRect(10, 40, 271, 81))
        self.code.setObjectName("code")
        self.decode = QtWidgets.QTextEdit(self.centralwidget)
        self.decode.setGeometry(QtCore.QRect(10, 150, 271, 81))
        self.decode.setObjectName("decode")
        second_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(second_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 295, 21))
        self.menubar.setObjectName("menubar")
        second_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(second_window)
        self.statusbar.setObjectName("statusbar")
        second_window.setStatusBar(self.statusbar)

        self.retranslateUi(second_window)
        QtCore.QMetaObject.connectSlotsByName(second_window)

    def retranslateUi(self, second_window):
        _translate = QtCore.QCoreApplication.translate
        second_window.setWindowTitle(_translate("second_window", "MainWindow"))
        self.run.setText(_translate("second_window", "run"))
        self.label.setText(_translate("second_window", "code"))
        self.label_2.setText(_translate("second_window", "decode"))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(202, 260)
        MainWindow.setMinimumSize(QtCore.QSize(202, 260))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ascii = QtWidgets.QPushButton(self.centralwidget)
        self.ascii.setGeometry(QtCore.QRect(30, 30, 141, 21))
        self.ascii.setObjectName("ascii")
        self.sibir = QtWidgets.QPushButton(self.centralwidget)
        self.sibir.setGeometry(QtCore.QRect(30, 60, 141, 21))
        self.sibir.setObjectName("sibir")
        self.xeming = QtWidgets.QPushButton(self.centralwidget)
        self.xeming.setGeometry(QtCore.QRect(30, 90, 141, 21))
        self.xeming.setObjectName("xeming")
        self.elias = QtWidgets.QPushButton(self.centralwidget)
        self.elias.setGeometry(QtCore.QRect(30, 120, 141, 21))
        self.elias.setObjectName("elias")
        self.CC = QtWidgets.QPushButton(self.centralwidget)
        self.CC.setGeometry(QtCore.QRect(30, 150, 141, 23))
        self.CC.setObjectName("CC")
        self.text_format = QtWidgets.QPushButton(self.centralwidget)
        self.text_format.setGeometry(QtCore.QRect(30, 180, 141, 23))
        self.text_format.setObjectName("text_format")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 202, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ascii.setText(_translate("MainWindow", "ASCII-1251"))
        self.sibir.setText(_translate("MainWindow", "сибирский"))
        self.xeming.setText(_translate("MainWindow", "хеминг"))
        self.elias.setText(_translate("MainWindow", "элиас"))
        self.CC.setText(_translate("MainWindow", "системы счисления"))
        self.text_format.setText(_translate("MainWindow", "форматирование текста"))


class Ui_Format_window(object):
    def setupUi(self, Format_window):
        Format_window.setObjectName("Format_window")
        Format_window.resize(294, 371)
        Format_window.setMinimumSize(QtCore.QSize(294, 371))
        self.centralwidget = QtWidgets.QWidget(Format_window)
        self.centralwidget.setObjectName("centralwidget")
        self.to_8 = QtWidgets.QPushButton(self.centralwidget)
        self.to_8.setGeometry(QtCore.QRect(20, 130, 131, 23))
        self.to_8.setObjectName("to_8")
        self.set_zero = QtWidgets.QPushButton(self.centralwidget)
        self.set_zero.setGeometry(QtCore.QRect(20, 170, 131, 23))
        self.set_zero.setObjectName("set_zero")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 130, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 170, 121, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.to_14 = QtWidgets.QPushButton(self.centralwidget)
        self.to_14.setGeometry(QtCore.QRect(20, 150, 131, 23))
        self.to_14.setObjectName("to_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 150, 121, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pole_input = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_input.setGeometry(QtCore.QRect(20, 10, 251, 111))
        self.pole_input.setObjectName("pole_input")
        self.pole_output = QtWidgets.QTextEdit(self.centralwidget)
        self.pole_output.setGeometry(QtCore.QRect(20, 200, 251, 111))
        self.pole_output.setObjectName("pole_output")
        Format_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Format_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 294, 21))
        self.menubar.setObjectName("menubar")
        Format_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Format_window)
        self.statusbar.setObjectName("statusbar")
        Format_window.setStatusBar(self.statusbar)

        self.retranslateUi(Format_window)
        QtCore.QMetaObject.connectSlotsByName(Format_window)

    def retranslateUi(self, Format_window):
        _translate = QtCore.QCoreApplication.translate
        Format_window.setWindowTitle(_translate("Format_window", "MainWindow"))
        self.to_8.setText(_translate("Format_window", "разбить по 8"))
        self.set_zero.setText(_translate("Format_window", "убрать ведущии нули"))
        self.pushButton_3.setText(_translate("Format_window", "в разработке"))
        self.pushButton_4.setText(_translate("Format_window", "в разработке"))
        self.to_14.setText(_translate("Format_window", "разбить по 15"))
        self.pushButton_6.setText(_translate("Format_window", "в разработке"))


class Ui_Error(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(296, 174)
        Dialog.setMinimumSize(QtCore.QSize(296, 174))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 261, 51))
        self.label.setObjectName("label")
        self.format_input = QtWidgets.QLabel(Dialog)
        self.format_input.setGeometry(QtCore.QRect(20, 70, 251, 51))
        self.format_input.setText("")
        self.format_input.setObjectName("format_input")
        self.button_ok = QtWidgets.QPushButton(Dialog)
        self.button_ok.setGeometry(QtCore.QRect(210, 140, 75, 23))
        self.button_ok.setObjectName("button_ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Вы ввели данные в неправильном формате.\n"
"Правильный формат ввода данных ниже."))
        self.button_ok.setText(_translate("Dialog", "OK"))


class Ui_CC_Window(object):
    def setupUi(self, CC_Window):
        CC_Window.setObjectName("CC_Window")
        CC_Window.resize(259, 385)
        CC_Window.setMinimumSize(QtCore.QSize(259, 385))
        self.centralwidget = QtWidgets.QWidget(CC_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.cc2 = QtWidgets.QTextEdit(self.centralwidget)
        self.cc2.setGeometry(QtCore.QRect(50, 30, 161, 51))
        self.cc2.setObjectName("cc2")
        self.cc8 = QtWidgets.QTextEdit(self.centralwidget)
        self.cc8.setGeometry(QtCore.QRect(50, 100, 161, 51))
        self.cc8.setObjectName("cc8")
        self.cc10 = QtWidgets.QTextEdit(self.centralwidget)
        self.cc10.setGeometry(QtCore.QRect(50, 170, 161, 51))
        self.cc10.setObjectName("cc10")
        self.cc16 = QtWidgets.QTextEdit(self.centralwidget)
        self.cc16.setGeometry(QtCore.QRect(50, 240, 161, 51))
        self.cc16.setObjectName("cc16")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(140, 310, 75, 23))
        self.run.setObjectName("run")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 150, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 220, 47, 13))
        self.label_4.setObjectName("label_4")
        self.set = QtWidgets.QPushButton(self.centralwidget)
        self.set.setGeometry(QtCore.QRect(50, 310, 75, 23))
        self.set.setObjectName("set")
        CC_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CC_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 259, 21))
        self.menubar.setObjectName("menubar")
        CC_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CC_Window)
        self.statusbar.setObjectName("statusbar")
        CC_Window.setStatusBar(self.statusbar)

        self.retranslateUi(CC_Window)
        QtCore.QMetaObject.connectSlotsByName(CC_Window)

    def retranslateUi(self, CC_Window):
        _translate = QtCore.QCoreApplication.translate
        CC_Window.setWindowTitle(_translate("CC_Window", "MainWindow"))
        self.run.setText(_translate("CC_Window", "run"))
        self.label.setText(_translate("CC_Window", "cc2"))
        self.label_2.setText(_translate("CC_Window", "cc8"))
        self.label_3.setText(_translate("CC_Window", "cc10"))
        self.label_4.setText(_translate("CC_Window", "cc16"))
        self.set.setText(_translate("CC_Window", "set"))